### ISSUE TITLE
[minor] Correct use of booleans

### ISSUE THREAD

**Issue by ale1313** [gomezlucas/RickandMorty-Challenge#7]
The comparison operator returns a boolean. You don't need to actually use a ternary to return a literal boolean

https://github.com/gomezlucas/RickandMorty-Challenge/blob/48007cc9fc2c27b5fb76922f57a82d196884f3e8/src/components/filter/Filter.js#L50

**Comment by gomezlucas** [comment]
Issue solved in Filter.js and in FilterLocation.js.
